name: Compile Sing-Box Rule Sets

on:
  push:
    paths:
      - '**/*.json'   # 只要 json 文件变化就触发

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装 Sing-Box（示例用 Linux x86_64 最新 release）
      - name: Install Sing-Box
        run: |
          wget  https://github.com/SagerNet/sing-box/releases/download/v1.12.11/sing-box-1.12.11-linux-amd64.tar.gz
          tar -xzf sing-box-1.12.11-linux-amd64.tar.gz
          chmod +x sing-box-1.12.11-linux-amd64
          sudo mv  sing-box-1.12.11-linux-amd64/sing-box /usr/local/bin/sing-box
          sing-box --version

      # 3. 编译 JSON 文件
      - name: Compile JSON to SRS
        run: |
          for file in *.json; do
            echo "Compiling $file ..."
            sing-box rule-set compile --output "${file%.json}.srs" "$file"
          done

      # 4. 上传生成的 SRS 文件（可选）
      - name: Upload compiled SRS
        uses: actions/upload-artifact@v4
        with:
          name: compiled-srs
          path: '*.srs'
